ads:
  enabled: true
  allowPostSessionAd: true
  allowRewarded: true
  dailyRewardCap: 5
  cooldownSeconds: 60
  allowedRewardTypes: [HINT, EXTRA_TIME]
  devMode: true

billing:
  dev-accept: true        # 개발 단계: 서버에서 영수증을 신뢰하고 30일 구독 처리
  default-days: 30

crypto:
  aesKeyBase64: "U3VwZXJTZWN1cmVLZXlTdXBlclNlY3VyZUtleVN1cGVyU2VjdXJlIQ==" # 예시(무작위 32바이트 base64)