play:
  package-name: com.healthcare.play
  # service-account-json: file:/etc/secrets/play-service.json

spring:
  datasource:
    url: jdbc:postgresql://192.168.56.103:5432/healthcare
    username: fhc
    password: fhc
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration